"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowUpRight, CheckCheck, Clock3, ShieldCheck, UsersRound } from "lucide-react";
import { useData } from "@/lib/use-data";
import { date, label, record, seconds, text, type CasePage, type Finding, type Intelligence, type Json, type Hypothesis } from "@/lib/types";
import type { ScreenProps } from "./workbench";
import { Badge, Button, Card, Empty } from "./ui";
import { CaseTable, DataState, Inspect, References } from "./data-display";

function Bars({items, title}: {items: Finding[]; title: string}) {
  const [selected, setSelected] = useState<Finding>();
  const maximum = Math.max(1, ...items.map(item => item.count));
  return <Card title={title} description="Observed exception associations; categories may overlap.">{!items.length ? <Empty>No measured observations in this cohort.</Empty> : <div className="bars">{items.map(item => <button className="bar-row" key={item.key} onClick={() => setSelected(item)} title={item.method}><span>{label(item.key)}</span><div className="bar-track"><i style={{width: `${item.count / maximum * 100}%`}} /></div><strong>{item.count}</strong></button>)}</div>}{selected && <div className="finding-detail"><div className="row-between"><h3>{label(selected.key)}</h3><Button variant="ghost" onClick={() => setSelected(undefined)}>Close</Button></div><p>{selected.method}</p><p className="muted">{selected.limitation}</p><References items={selected.references} /><Inspect value={selected} title="Inspect calculation and references" /></div>}</Card>;
}
export function Overview(props: ScreenProps) {
  const report = useData<Intelligence>("intelligence/report", props.revision);
  const telemetry = useData<Json>("reliability/telemetry", props.revision);
  const cases = useData<CasePage>("workbench/cases?limit=6", props.revision);
  return <><DataState state={report}>{data => <><div className="source-line"><span className="live-dot" /> Read from PostgreSQL <span>Last 30-day cohort · {data.case_count} cases · generated {date(data.generated_at)}</span>{data.truncated && <Badge value="TRUNCATED" />}</div><div className="kpi-grid">{[
    {key: "open_cases", name: "Open cases", description: "Current state in selected cohort", icon: Clock3},
    {key: "awaiting_human", name: "Awaiting employee", description: "Current human review exposure", icon: UsersRound},
    {key: "verified_resolutions", name: "Verified resolutions", description: "Independent verification chain", icon: CheckCheck},
    {key: "sla_overdue_current", name: "SLA exposure", description: "Currently overdue, still open", icon: ShieldCheck},
  ].map(metric => <Card key={metric.key} className="kpi"><div className="kpi-top"><span>{metric.name}</span><metric.icon size={18} /></div><strong>{data.overview[metric.key] ?? "Unavailable"}</strong><p>{metric.description}</p></Card>)}</div><div className="two-columns"><Bars items={data.categories} title="Exception categories" /><Card title="Measured workflow durations" description="Completed intervals only; incomplete cases remain visible."><div className="duration-list">{data.bottlenecks.map(metric => <div key={metric.key}><span>{label(metric.key)}</span><strong>{seconds(metric.median_seconds)}</strong><small>{metric.completed} completed · {metric.incomplete} incomplete · {metric.invalid_order} invalid</small></div>)}</div></Card></div></>}</DataState><div className="two-columns"><Card title="Worker queue" description="Current global synthetic queue counts."><DataState state={telemetry}>{data => <><div className="queue-grid">{Object.entries(record(data.queue_by_status)).map(([status, count]) => <div key={status}><Badge value={status} /><strong>{text(count)}</strong></div>)}</div><p className="muted">Retries beyond first attempt: {text(data.retry_attempts)} · Shadow observations: {text(data.shadow_count)}</p>{!Object.keys(record(data.queue_by_status)).length && <Empty>No queued work is recorded.</Empty>}</>}</DataState></Card><Card title="Authority remains explicit" description="Each step has a separate persisted boundary."><div className="authority-steps"><span>Observed evidence</span><span>Supervisor recommendation</span><span>Deterministic control</span><span>Action approval, if required</span><span>Execution → independent verification</span></div><Link className="text-link" href="/approvals">Review human handovers <ArrowUpRight size={14} /></Link></Card></div><Card title="Recently updated cases" action={<Link className="text-link" href="/cases">View all cases <ArrowUpRight size={14} /></Link>}><DataState state={cases}>{data => <CaseTable items={data.items} />}</DataState></Card></>;
}
export function Cases(props: ScreenProps & {query: string}) {
  const [search, setSearch] = useState(props.query), [applied, setApplied] = useState(props.query), [status, setStatus] = useState(""), [priority, setPriority] = useState(""), [offset, setOffset] = useState(0);
  const params = new URLSearchParams({q: applied, limit: "25", offset: String(offset)});
  if (status) params.set("status", status); if (priority) params.set("priority", priority);
  const state = useData<CasePage>(`workbench/cases?${params}`, props.revision);
  return <Card><form className="filters" onSubmit={e => {e.preventDefault(); setApplied(search); setOffset(0);}}><input aria-label="Filter cases" placeholder="Case number or observed summary" value={search} onChange={e => setSearch(e.target.value)} /><select aria-label="Filter status" value={status} onChange={e => {setStatus(e.target.value); setOffset(0);}}><option value="">All statuses</option>{["DETECTED", "TRIAGED", "INVESTIGATION_QUEUED", "INVESTIGATING", "AWAITING_DECISION", "AWAITING_HUMAN", "APPROVED", "EXECUTION_QUEUED", "EXECUTING", "VERIFYING", "RESOLVED", "BLOCKED", "ESCALATED", "FAILED"].map(value => <option key={value}>{value}</option>)}</select><select aria-label="Filter priority" value={priority} onChange={e => {setPriority(e.target.value); setOffset(0);}}><option value="">All priorities</option>{["LOW", "MEDIUM", "HIGH", "CRITICAL"].map(value => <option key={value}>{value}</option>)}</select><Button type="submit">Apply filters</Button></form><DataState state={state}>{data => <><CaseTable items={data.items} /><div className="pagination"><span>{data.total} matching cases · {data.items.length ? offset + 1 : 0}–{offset + data.items.length}</span><Button variant="secondary" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 25))}>Previous</Button><Button variant="secondary" disabled={offset + data.items.length >= data.total} onClick={() => setOffset(offset + 25)}>Next</Button></div></>}</DataState></Card>;
}
function Hypotheses({items, title}: {items: Hypothesis[]; title: string}) { return <Card title={title} description="Advisory associations; no autonomous policy or routing changes.">{!items.length ? <Empty>No supported advisory hypotheses are available.</Empty> : <div className="hypotheses">{items.map((item, index) => <article key={index}><p className="eyebrow">CONTRIBUTING FACTOR HYPOTHESIS</p><h3>{item.suspected_factor}</h3><p>{item.next_step}</p><p className="muted">{item.confidence_limitation}</p><References items={item.supporting_evidence} />{!!item.missing_information.length && <p>Missing information: {item.missing_information.join("; ")}</p>}{!!item.contradictory_evidence.length && <><strong>Contradictory observations</strong><References items={item.contradictory_evidence} /></>}<Inspect value={item} title="Inspect supporting and contradictory evidence" /></article>)}</div>}</Card>; }
export function IntelligenceView(props: ScreenProps) {
  const state = useData<Intelligence>("intelligence/report", props.revision);
  return <DataState state={state}>{data => <><div className="source-line">Measured cohort: {date(data.window_start)} – {date(data.window_end)} · {data.case_count} cases {data.truncated && <Badge value="TRUNCATED" />}</div><div className="two-columns"><Bars items={data.categories} title="Observed exception frequency" /><Bars items={data.recurrences} title="Recurring observed systems / endpoints" /></div><Card title="Process bottlenecks"><div className="table-scroll"><table><thead><tr><th>Workflow interval</th><th>Median</th><th>Completed</th><th>Incomplete</th><th>Invalid order</th></tr></thead><tbody>{data.bottlenecks.map(item => <tr key={item.key}><td>{label(item.key)}</td><td>{seconds(item.median_seconds)}</td><td>{item.completed}</td><td>{item.incomplete}</td><td>{item.invalid_order}</td></tr>)}</tbody></table></div></Card><Hypotheses items={data.hypotheses} title="Contributing-factor hypotheses" /><Hypotheses items={data.prevention} title="Candidate prevention improvements" /><Card title="Interpretation limits"><ul className="plain-list">{data.limitations.map(item => <li key={item}>{item}</li>)}</ul></Card></>}</DataState>;
}
