"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowUpRight, CheckCheck, ShieldCheck } from "lucide-react";
import { useData } from "@/lib/use-data";
import { api } from "@/lib/api";
import { date, label, record, rows, text, words, type CaseDetail, type Json, type Replay } from "@/lib/types";
import type { ScreenProps } from "./workbench";
import { Badge, Button, Card, Empty } from "./ui";
import { DataState, Inspect, RecordList, Failure } from "./data-display";

export function ControlsPanel({detail, shadowOnly = false, ...props}: ScreenProps & {detail: CaseDetail; shadowOnly?: boolean}) {
  const [review, setReview] = useState(""), [policy, setPolicy] = useState(""), [payment, setPayment] = useState(""), [key, setKey] = useState("");
  const reviewId = review || text(detail.supervisor_reviews[0]?.id, "");
  const policyId = policy || detail.authorizations[0]?.policy_version_id || text(detail.policies.find(row => row.is_active)?.id, "");
  const paymentId = payment || text(detail.exceptions[0]?.source_reference, "");
  async function evaluate(shadow: boolean) {
    const effectKey = key || crypto.randomUUID(); setKey(effectKey);
    await props.mutate(shadow ? `reliability/cases/${detail.case.id}/shadow` : `cases/${detail.case.id}/controls/evaluate`, {
      supervisor_review_id: reviewId, policy_version_id: policyId, action: {action_type: "REPLAY_CONFIRMATION", payment_id: paymentId, idempotency_key: effectKey},
    });
  }
  return <Card title={shadowOnly ? "Non-executable shadow evaluation" : "Deterministic action controls"} description="Supported action: synthetic confirmation replay. Current source and policy checks remain authoritative."><div className="form-grid"><label>Supervisor recommendation<select value={reviewId} onChange={e => setReview(e.target.value)}><option value="">Select a completed review</option>{detail.supervisor_reviews.map(row => <option key={text(row.id)} value={text(row.id)}>{label(text(row.outcome))} · {text(row.id).slice(0, 12)}</option>)}</select></label><label>Policy version<select value={policyId} onChange={e => setPolicy(e.target.value)}><option value="">Select an existing policy</option>{detail.policies.map(row => <option key={text(row.id)} value={text(row.id)}>Version {text(row.version)} · {row.is_active ? "Active" : "Inactive"} · {text(row.id).slice(0, 10)}</option>)}</select></label><label>Observed payment reference<input value={paymentId} onChange={e => setPayment(e.target.value)} /></label><label>Action idempotency key<input value={key} placeholder="Generated once on evaluation" onChange={e => setKey(e.target.value)} maxLength={200} /></label></div><div className="button-row"><Button variant="secondary" disabled={props.busy || !reviewId || !policyId || !paymentId} onClick={() => evaluate(true)}>Evaluate shadow</Button>{!shadowOnly && props.identity.roles.includes("WORKER") && <Button disabled={props.busy || !reviewId || !policyId || !paymentId} onClick={() => evaluate(false)}><ShieldCheck size={15} /> Evaluate operational controls</Button>}</div>{!reviewId && <p className="muted">A completed, source-backed Supervisor review is required.</p>}</Card>;
}
function EvidenceView({items}: {items: Json[]}) { return <Card title="Observed source evidence" description="Source observations and retrieved evidence retain their identifiers and time windows.">{!items.length ? <Empty>No source evidence has been linked or retrieved.</Empty> : <div className="evidence-grid">{items.map((item, index) => <article className="evidence-item" id={text(item.id)} key={`${text(item.id)}-${index}`}><div className="row-between"><strong>{text(item.source_system)}</strong><Badge value={text(item.kind)} /></div><p className="mono">{text(item.source_record_id)}</p><dl><dt>Occurred</dt><dd>{date(item.occurred_at)}</dd><dt>Available / retrieved</dt><dd>{date(item.available_at)}</dd></dl><Inspect value={item} title="Inspect observed fields and provenance" /></article>)}</div>}</Card>; }
export function CaseView(props: ScreenProps & {caseId: string}) {
  const state = useData<CaseDetail>(`workbench/cases/${props.caseId}`, props.revision);
  const [tab, setTab] = useState("summary");
  const [relationships, setRelationships] = useState<Json>(), [relationshipError, setRelationshipError] = useState<Error>();
  const tabs = ["summary", "evidence", "investigations", "controls", "simulation", "queue"];
  return <DataState state={state}>{detail => <><Card><div className="case-title"><div><p className="eyebrow">{detail.case.case_number}</p><h2>{detail.case.summary ?? "Observed operations exception"}</h2><p>Detected {date(detail.case.created_at)} · SLA deadline {date(detail.case.sla_deadline)}</p></div><Badge value={detail.case.status} /></div><div className="button-row"><Link className="text-link" href={`/timeline?case=${detail.case.id}`}>Open recorded timeline <ArrowUpRight size={14} /></Link><Link className="text-link" href={`/shadow?case=${detail.case.id}`}>Shadow & replay <ArrowUpRight size={14} /></Link>{props.identity.roles.includes("WORKER") && <Button variant="secondary" disabled={props.busy} onClick={() => props.mutate(`cases/${detail.case.id}/orchestrate`)}>Schedule eligible case work</Button>}</div><div className="tabs" role="tablist" aria-label="Case sections">{tabs.map(name => <button key={name} id={`tab-${name}`} role="tab" aria-selected={tab === name} aria-controls="case-tabpanel" tabIndex={tab === name ? 0 : -1} onClick={() => setTab(name)} onKeyDown={e => {if (["ArrowRight", "ArrowLeft"].includes(e.key)) {e.preventDefault(); const next = tabs[(tabs.indexOf(name) + (e.key === "ArrowRight" ? 1 : tabs.length - 1)) % tabs.length]; setTab(next); document.getElementById(`tab-${next}`)?.focus();}}}>{label(name)}</button>)}</div></Card>{detail.truncated && <div className="notice">Record caps reached; this view is partial. Use the paginated case APIs for additional records.</div>}<div id="case-tabpanel" role="tabpanel" aria-labelledby={`tab-${tab}`}>
    {tab === "summary" && <><div className="two-columns"><Card title="Detected exceptions"><RecordList items={detail.exceptions} titleKey="exception_type" /></Card><Card title="Latest classification, priority and routing">{detail.assessments[0] ? <Inspect value={detail.assessments[0]} title="Inspect deterministic assessment and input observations" /> : <Empty>No classification has been persisted.</Empty>}<div className="tag-row">{detail.case.categories.map(value => <Badge key={value} value={value} />)}</div></Card></div><Card title="Incident relationships" description="Observed shared facts, membership corrections, split/merge history and contradictions.">{!detail.case.incident_ids.length ? <Empty>This case has no current incident membership.</Empty> : detail.case.incident_ids.map(id => <Button key={id} variant="secondary" onClick={async () => {try {setRelationships(await api<Json>(`intelligence/incidents/${id}/relationships`)); setRelationshipError(undefined);} catch (e) {setRelationshipError(e instanceof Error ? e : new Error("Relationship request failed"));}}}>Inspect incident {id.slice(0, 12)}</Button>)}{relationshipError && <Failure error={relationshipError} />}{relationships && <Inspect value={relationships} title="Inspect relationships and historical membership" />}</Card></>}
    {tab === "evidence" && <EvidenceView items={detail.evidence} />}
    {tab === "investigations" && <InvestigationRecords detail={detail} />}
    {tab === "controls" && <><ControlsPanel {...props} detail={detail} /><Card title="Action-bound authorizations" description="A recommendation, simulation or shadow result cannot substitute for this record.">{!detail.authorizations.length ? <Empty>No deterministic control evaluation is recorded.</Empty> : detail.authorizations.map(item => <article className="authorization" key={item.id}><div className="row-between"><strong>Authorization {item.id.slice(0, 12)}</strong><Badge value={item.outcome} /></div><p>Expires {date(item.expires_at)} · policy {item.policy_version_id ?? "Unavailable"}</p>{item.reasons.map(reason => <p className="control-reason" key={reason}>{label(reason)}</p>)}{item.approval && <p>Action approval: <Badge value={item.approval.status} /> · {item.approval.assigned_role}</p>}<Inspect value={item} title="Inspect action and control decision" />{props.identity.roles.includes("WORKER") && <div className="button-row"><Button variant="secondary" disabled={props.busy || !["AUTO_ELIGIBLE", "HUMAN_APPROVAL_REQUIRED"].includes(item.outcome) || new Date(item.expires_at).getTime() <= Date.now()} onClick={() => props.mutate(`authorizations/${item.id}/simulate`)}>Preview hypothetical outcome</Button><Button disabled={props.busy || !["AUTO_ELIGIBLE", "HUMAN_APPROVAL_REQUIRED"].includes(item.outcome) || (item.outcome === "HUMAN_APPROVAL_REQUIRED" && item.approval?.status !== "APPROVED") || new Date(item.expires_at).getTime() <= Date.now()} onClick={() => props.mutate("actions/submit", {authorization_id: item.id})}>Submit synthetic confirmation replay</Button></div>}</article>)}</Card><ActualActions caseId={detail.case.id} revision={props.revision} /></>}
    {tab === "simulation" && <Card title="Persisted what-if simulations" description="Hypothetical projections do not establish executed effects or successful resolution."><RecordList items={detail.simulations} titleKey="outcome" empty="No hypothetical preview has been persisted." /></Card>}
    {tab === "queue" && <Card title="Durable queue and attempts"><RecordList items={detail.tasks.tasks} titleKey="task_type" /><Inspect value={detail.tasks.events} title="Inspect lease, attempt and queue event history" /></Card>}
  </div></>}</DataState>;
}
function ActualActions({caseId, revision}: {caseId: string; revision: number}) { const state = useData<Json[]>(`cases/${caseId}/actions`, revision); return <Card title="Actual execution and independent verification" description="Only a successful independent verification can establish resolution."><DataState state={state}>{items => <RecordList items={items} titleKey="status" empty="No executable action has been submitted." />}</DataState></Card>; }
function InvestigationRecords({detail}: {detail: CaseDetail}) {
  return <><Card title="Specialist investigation attempts" description="Model summaries and hypotheses are recorded interpretations; predicate validation and source references are inspectable.">{!detail.investigations.length ? <Empty>No specialist attempt is recorded.</Empty> : detail.investigations.map(run => <article className="investigation" key={text(run.id)}><div className="row-between"><h3>{label(text(run.role))}</h3><Badge value={text(run.status)} /></div><p>{text(record(run.result).summary, "No accepted summary")}</p><p className="muted">Attempt {text(run.attempt)} · {text(run.model)} · {date(run.started_at)} → {date(run.completed_at)}</p>{words(record(run.result).missing_evidence).map(item => <p className="control-reason" key={item}>{item}</p>)}<Inspect value={run} title="Inspect findings, hypotheses, missing evidence and predicate validation" /></article>)}</Card><Card title="Supervisor review" description="Advisory recommendation; execution authority remains NOT EVALUATED.">{!detail.supervisor_reviews.length ? <Empty>No Supervisor review has completed.</Empty> : detail.supervisor_reviews.map(review => <article className="investigation" key={text(review.id)}><div className="row-between"><strong>{text(record(review.result).summary)}</strong><Badge value={text(review.outcome)} /></div><p>Proposed action: {text(record(review.result).proposed_action, "None")}</p><Inspect value={review} title="Inspect supported conclusions, disagreements and additional checks" /></article>)}</Card></>;
}
export function Investigations(props: ScreenProps & {caseId: string}) { const state = useData<CaseDetail>(props.caseId ? `workbench/cases/${props.caseId}` : null, props.revision); return props.caseId ? <DataState state={state}>{detail => <><InvestigationRecords detail={detail} /><EvidenceView items={detail.evidence} /><HistoricalContext {...props} detail={detail} /></>}</DataState> : <Empty>Select an available case to inspect investigations.</Empty>; }
function HistoricalContext(props: ScreenProps & {detail: CaseDetail}) {
  const [category, setCategory] = useState(text(props.detail.exceptions[0]?.exception_type, ""));
  const [context, setContext] = useState<Json>(), [error, setError] = useState<Error>();
  return <Card title="Retrieve reviewed historical context" description="Historical memory cannot replace current source evidence or authorize an action."><form className="filters" onSubmit={async e => {e.preventDefault(); try {setContext(await api<Json>(`cases/${props.detail.case.id}/memory/retrieve?category=${encodeURIComponent(category)}`)); setError(undefined);} catch (e) {setError(e instanceof Error ? e : new Error("Memory unavailable"));}}}><label>Observed exception category<input value={category} onChange={e => setCategory(e.target.value)} required /></label><Button variant="secondary" type="submit">Retrieve eligible memory</Button></form>{error && <Failure error={error} />}{context && <><p className="context-label">{text(context.label)}</p>{!rows(context.memories).length && <Empty>No eligible reviewed historical memory is available. Current investigation continues independently.</Empty>}<Inspect value={context} title="Inspect retrieval eligibility, provenance and guidance status" /></>}</Card>;
}
export function Timeline(props: ScreenProps & {caseId: string}) {
  const [time, setTime] = useState(""), [cutoff, setCutoff] = useState("");
  const state = useData<Replay>(props.caseId ? `reliability/cases/${props.caseId}/replay${cutoff ? `?as_of=${encodeURIComponent(cutoff)}` : ""}` : null, props.revision);
  if (!props.caseId) return <Empty>Select a case for recorded replay.</Empty>;
  return <><Card title="Decision-context replay" description="Reconstruct recorded availability at a timestamp; replay never executes or authorizes."><form className="filters" onSubmit={e => {e.preventDefault(); setCutoff(time ? new Date(time).toISOString() : "");}}><label>As-of time (your local timezone)<input type="datetime-local" step="1" value={time} onChange={e => setTime(e.target.value)} /></label><Button type="submit" variant="secondary">Replay recorded context</Button><Button type="button" variant="ghost" onClick={() => {setTime(""); setCutoff("");}}>Present context</Button></form></Card><DataState state={state}>{report => <><div className="source-line">Historical cutoff: {date(report.as_of)} · {report.truncated ? "Partial history — record cap reached" : "Within record caps"}</div><Card title="Recorded workflow timeline"><div className="timeline">{report.timeline.length ? report.timeline.map((event, index) => <article key={`${text(event.id)}-${index}`}><div className="timeline-dot"><CheckCheck size={12} /></div><div className="timeline-meta"><time>{date(event.at)}</time><strong>{label(text(event.kind))}</strong><Badge value={text(event.basis)} /></div><p>{text(record(event.payload).summary, text(record(event.payload).outcome, text(record(event.payload).detail, "Recorded transition or decision")))}</p>{event.actor != null && <p className="muted">Actor: {text(event.actor)}</p>}<Inspect value={event} title="Inspect decision, policy / approval reference and recorded details" /></article>) : <Empty>No historical transitions exist before this cutoff.</Empty>}</div></Card><div className="two-columns"><Card title={`Known at cutoff · ${report.evidence_known_at_time.length}`} description="Occurrence, ingestion and link/retrieval availability are checked."><RecordList items={report.evidence_known_at_time} titleKey="source_system" /></Card><Card title={`Observed afterward · ${report.evidence_observed_later.length}`} description="These observations were unavailable to earlier decisions."><RecordList items={report.evidence_observed_later} titleKey="source_system" /></Card></div><Card title="Reconstruction limitations"><ul className="plain-list">{report.reconstruction_limitations.map(item => <li key={item}>{item}</li>)}</ul></Card></>}</DataState></>;
}
export function Shadow(props: ScreenProps & {caseId: string}) {
  const detail = useData<CaseDetail>(props.caseId ? `workbench/cases/${props.caseId}` : null, props.revision);
  const history = useData<Json[]>(props.caseId ? `reliability/cases/${props.caseId}/shadow` : null, props.revision);
  const comparison = useData<Json>(props.caseId ? `reliability/cases/${props.caseId}/shadow-comparison` : null, props.revision);
  if (!props.caseId) return <Empty>Select a case to observe shadow results.</Empty>;
  return <><div className="context-label">SHADOW · NOT EVALUATED FOR AUTHORIZATION · EXECUTION PERMITTED: FALSE</div><DataState state={detail}>{data => <ControlsPanel {...props} detail={data} shadowOnly />}</DataState><div className="two-columns"><Card title="Persisted shadow observations" description="Isolated observations have no usable authorization ID."><DataState state={history}>{items => <RecordList items={items} titleKey="outcome" />}</DataState></Card><Card title="Comparison with independently established outcome"><DataState state={comparison}>{data => <><p><Badge value={data.independently_verified_resolution ? "INDEPENDENTLY VERIFIED RESOLUTION" : "NO INDEPENDENTLY VERIFIED RESOLUTION"} /></p><p>{text(data.limitation)}</p><Inspect value={data} title="Inspect actual verification and comparison timing" /></>}</DataState></Card></div><Timeline {...props} /></>;
}
