"use client";
import Link from "next/link";
import { useState, type ReactNode } from "react";
import { Copy, ExternalLink, LoaderCircle } from "lucide-react";
import { ApiError } from "@/lib/api";
import { label, date, text, type Json, type Reference, type CaseSummary } from "@/lib/types";
import { Badge, Button, Empty } from "./ui";
export function Loading() { return <div className="loading" role="status"><LoaderCircle size={20} className="spin" /> Loading persisted records…</div>; }
export function Failure({error, retry}: {error: Error; retry?: () => void}) { return <div className="notice error" role="alert"><strong>{error instanceof ApiError && error.status === 403 ? "Permission denied" : "Unable to load records"}</strong><p>{error.message}</p>{retry && <Button variant="secondary" onClick={retry}>Retry</Button>}</div>; }
export function DataState<T>({state, children}: {state: {data?: T; error?: Error; loading: boolean}; children: (data: T) => ReactNode}) { if (state.loading) return <Loading />; if (state.error) return <Failure error={state.error} />; return state.data ? children(state.data) : <Empty />; }
export function Inspect({value, title = "Inspect source record"}: {value: unknown; title?: string}) { const [copied, setCopied] = useState(false); return <details className="inspect"><summary>{title}</summary><Button variant="ghost" onClick={async () => { try { await navigator.clipboard.writeText(JSON.stringify(value, null, 2)); setCopied(true); } catch { setCopied(false); } }}><Copy size={13} />{copied ? "Copied" : "Copy record"}</Button><pre>{JSON.stringify(value, null, 2)}</pre></details>; }
export function References({items}: {items: Reference[]}) { return <div className="references">{items.map((ref, index) => ref.case_id ? <Link key={`${ref.id}-${index}`} href={`/cases/${ref.case_id}#${ref.id}`} title={ref.id}>{label(ref.kind)} · {ref.id.slice(0, 12)} <ExternalLink size={11} /></Link> : <span key={`${ref.id}-${index}`} title={ref.id}>{label(ref.kind)} · {ref.id}</span>)}</div>; }
export function CaseTable({items}: {items: CaseSummary[]}) { if (!items.length) return <Empty>No cases match these filters.</Empty>; return <div className="table-scroll"><table><thead><tr><th>Case / observed exception</th><th>Status</th><th>Priority</th><th>SLA deadline</th><th>Last updated</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><Link className="case-link" href={`/cases/${item.id}`}>{item.case_number}</Link><p className="cell-sub">{item.summary ?? "Summary not recorded"}</p><div className="tag-row">{item.categories.map(category => <span className="small-tag" key={category}>{label(category)}</span>)}</div></td><td><Badge value={item.status} /></td><td><span className={`priority ${item.priority.toLowerCase()}`}>● {item.priority}</span></td><td>{date(item.sla_deadline)}</td><td>{date(item.updated_at)}</td></tr>)}</tbody></table></div>; }
export function RecordList({items, titleKey = "id", empty}: {items: Json[]; titleKey?: string; empty?: string}) { if (!items.length) return <Empty>{empty}</Empty>; return <div className="record-list">{items.map((item, index) => <article id={text(item.id, `record-${index}`)} key={text(item.id, String(index))}><div className="row-between"><strong>{text(item[titleKey])}</strong>{typeof item.status === "string" && <Badge value={item.status} />}</div><Inspect value={item} /></article>)}</div>; }
